/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cmpt370_timetracker_JNI */

#ifndef _Included_com_cmpt370_timetracker_JNI
#define _Included_com_cmpt370_timetracker_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cmpt370_timetracker_JNI
 * Method:    CurrentIdleTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_cmpt370_timetracker_JNI_CurrentIdleTime
  (JNIEnv *, jobject);

/*
 * Class:     com_cmpt370_timetracker_JNI
 * Method:    RegisterHotKey
 * Signature: (Ljavafx/scene/input/KeyCode;)I
 */
JNIEXPORT jint JNICALL Java_com_cmpt370_timetracker_JNI_RegisterHotKey
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cmpt370_timetracker_JNI
 * Method:    UnregisterHotKey
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cmpt370_timetracker_JNI_UnregisterHotKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cmpt370_timetracker_JNI
 * Method:    QueryHotkeyState
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cmpt370_timetracker_JNI_QueryHotkeyState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cmpt370_timetracker_JNI
 * Method:    GetFocusedAppPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cmpt370_timetracker_JNI_GetFocusedAppPath
  (JNIEnv *, jobject);

/*
 * Class:     com_cmpt370_timetracker_JNI
 * Method:    InitializeHotkeyPolling
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_cmpt370_timetracker_JNI_InitializeHotkeyPolling
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
